options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/aviclear-497604/cloud-run-source-deploy/fpa-revops-agents/fpa-api:$COMMIT_SHA",
        "-f",
        "agents/Dockerfile",
        "./agents",
      ]

images:
  - "us-central1-docker.pkg.dev/aviclear-497604/cloud-run-source-deploy/fpa-revops-agents/fpa-api:$COMMIT_SHA"
